### ISSUE TITLE
Question: Is this library safe from chosen-plaintext attacks

### ISSUE THREAD

**Issue by octotep** [geometryresearch/mental-poker#9]
I'm very inexperienced wrt mental poker and cryptography so I'm hoping this is a question you could answer! Is this library weak to chosen-plaintext attacks? I stumbled upon this paper, [On the Security of an Efficient TPP-Free Mental Poker Protocol](https://crises-deim.urv.cat/web/docs/publications/conferences/628.pdf), and I lack the mathematical background to know whether the El-gamal used in this library is weak to the attack mentioned in the paper (or if the paper is accurate in the first place for that matter). Thank you for your time and thank you for this library!

**Comment by nmohnblatt** [comment]
Hi! Thanks for the question and linking to this paper, interesting read!

This library is safe against chosen-plaintext attacks under the assumption that the decisional Diffie-Hellman problem is hard. This usually holds for most elliptic curves that we use in practice. Found these slides that explain the ElGamal security proof well https://cs.wellesley.edu/~cs310/lectures/27_el_gamal_slides_handouts.pdf

The reason why the Zhao _et al._ protocol breaks is because they don't seem to be applying ElGamal correctly! They use the same hiding factor for every card, whereas ElGamal encryption requires a new random value for each message you encrypt.

**Comment by nmohnblatt** [comment]
An extra note: ElGamal encryption is not secure against chosen-ciphertext attacks. The Barnett-Smart protocol (on which this library is based) defends against these attacks by not giving players the choice of their ciphertexts: players are always required to prove that the values they publish are maskings and/or remaskings of the existing cards
